import { Tool } from "./interfaces/tool";
import { Weapon } from "./interfaces/weapon";
import { Armor } from "./interfaces/armor";
import { Ring } from "./interfaces/ring";
import { Spell } from "./interfaces/spell";
import { Art } from "./interfaces/art";
import { Feat } from "./interfaces/feat";
import { Destiny } from "./interfaces/destiny";
import { Junk } from "./interfaces/junk";
import { Item } from "./interfaces/item";

export const TOOLS: Tool[] = [
  { id: 0, name: 'Estus', itemType: "TOOL", icon: '/assets/images/icons/00_items/MENU_Knowledge_00009.PNG', description: 'Drink to recover HP!', tags: [] },
  { id: 1, name: 'Ashen Estus', itemType: "TOOL", icon: '/assets/images/icons/00_items/MENU_Knowledge_00013.PNG', description: 'Drink to recover FP!', tags: [] },
  { id: 2, name: 'Bloodred Moss Bulb', itemType: "TOOL", icon: '/assets/images/icons/00_items/MENU_Knowledge_00016.PNG', description: 'Recoveres Bleed status', tags: [] },
  { id: 3, name: 'Purple Moss Bulb', itemType: "TOOL", icon: '/assets/images/icons/00_items/MENU_Knowledge_00018.PNG', description: 'Recovers Toxic status', tags: [] },
  { id: 4, name: 'Greenblossom Bulb', itemType: "TOOL", icon: '/assets/images/icons/00_items/MENU_Knowledge_00250.PNG', description: 'Recovers Poison status', tags: [] },
  { id: 5, name: 'Pale Pine Resin', itemType: "TOOL", icon: '/assets/images/icons/00_items/MENU_Knowledge_00037.PNG', description: 'Add magic damage to weapon', tags: [] },
  { id: 6, name: 'Gold Pine Resin', itemType: "TOOL", icon: '/assets/images/icons/00_items/MENU_Knowledge_00036.PNG', description: 'Add lightning damage to weapon', tags: [] },
  { id: 7, name: 'Blue Bug Pellet', itemType: "TOOL", icon: '/assets/images/icons/00_items/MENU_Knowledge_00205.PNG', description: 'Gain magic resistance', tags: [] },
  { id: 8, name: 'Firebomb', itemType: "TOOL", icon: '/assets/images/icons/00_items/MENU_Knowledge_00028.PNG', description: 'Deal aoe fire damage', tags: [] },
  { id: 9, name: 'Throwing Knives', itemType: "TOOL", icon: '/assets/images/icons/00_items/MENU_Knowledge_00025.PNG', description: 'Ranged physical damage', tags: [] }
  
  ];
  export const WEAPONS: Weapon[] = [
    { id: 0, name: 'Dagger', itemType: "WEAPON", icon: '/assets/images/icons/01_weapons/MENU_Knowledge_01001.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Dagger"] },
    { id: 1, name: 'Short Sword', itemType: "WEAPON", icon: '/assets/images/icons/01_weapons/MENU_Knowledge_01012.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Sword"] },
    { id: 2, name: 'Rapier', itemType: "WEAPON", icon: '/assets/images/icons/01_weapons/MENU_Knowledge_01016.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Sword"] },
    { id: 3, name: 'Twin Curved Swords', itemType: "WEAPON", icon: '/assets/images/icons/01_weapons/MENU_Knowledge_01165.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Sword"] },
    { id: 4, name: 'Halberd', itemType: "WEAPON", icon: '/assets/images/icons/01_weapons/MENU_Knowledge_01225.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Halberd"] },
    { id: 5, name: 'Hand Axe', itemType: "WEAPON", icon: '/assets/images/icons/01_weapons/MENU_Knowledge_01071.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Axe"] },
    { id: 6, name: 'Wooden Club', itemType: "WEAPON", icon: '/assets/images/icons/01_weapons/MENU_Knowledge_01084.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Hammer"] },
    { id: 7, name: 'Sorcerers Staff', itemType: "WEAPON", icon: '/assets/images/icons/01_weapons/MENU_Knowledge_01139.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Sorcery"] },
    { id: 8, name: 'Pyromancy Flame', itemType: "WEAPON", icon: '/assets/images/icons/01_weapons/MENU_Knowledge_01248.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Miracles"] },
    { id: 9, name: 'Talisman', itemType: "WEAPON", icon: '/assets/images/icons/01_weapons/MENU_Knowledge_01246.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Pyromancy"] }
  ];
  export const ARMORS: Armor[] = [
    { id: 0, name: 'Robe', itemType: "ARMOR", icon: '/assets/images/icons/03_armor/MENU_Knowledge_03077.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Light"] },
    { id: 1, name: 'Chain Mail', itemType: "ARMOR", icon: '/assets/images/icons/03_armor/MENU_Knowledge_03005.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Medium"] },
    { id: 2, name: 'Plate Mail', itemType: "ARMOR", icon: '/assets/images/icons/03_armor/MENU_Knowledge_03085.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Heavy"] },
    { id: 3, name: 'Gravewarden Robes', itemType: "ARMOR", icon: '/assets/images/icons/03_armor/MENU_Knowledge_03165.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Medium"] },
    { id: 4, name: 'Ivory Studded Armor', itemType: "ARMOR", icon: '/assets/images/icons/03_armor/MENU_Knowledge_03157.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Medium"] },
    { id: 5, name: 'Ivory Leather Wrappings', itemType: "ARMOR", icon: '/assets/images/icons/03_armor/MENU_Knowledge_03173.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Light"] },
    { id: 6, name: 'Abbots Robes', itemType: "ARMOR", icon: '/assets/images/icons/03_armor/MENU_Knowledge_03385.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Light"] },
    { id: 7, name: 'Cormian White Leather Armor', itemType: "ARMOR", icon: '/assets/images/icons/03_armor/MENU_Knowledge_03381.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Medium"] },
    { id: 8, name: 'Gyrm Heavy Armor', itemType: "ARMOR", icon: '/assets/images/icons/03_armor/MENU_Knowledge_03137.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Heavy"] },
    { id: 9, name: 'Corvian Feather Robes', itemType: "ARMOR", icon: '/assets/images/icons/03_armor/MENU_Knowledge_03177.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Light"] }
  ];
  export const RINGS: Ring[] = [
    { id: 0, name: 'Ring of Sacrifice', itemType: "RING", icon: '/assets/images/icons/05_rings/MENU_Knowledge_05048.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: [] },
    { id: 1, name: 'Dark Wood Grain Ring', itemType: "RING", icon: '/assets/images/icons/05_rings/MENU_Knowledge_05037.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: [] },
    { id: 2, name: 'Hornet Ring', itemType: "RING", icon: '/assets/images/icons/05_rings/MENU_Knowledge_05073.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: [] },
    { id: 3, name: 'Hawkeye Ring', itemType: "RING", icon: '/assets/images/icons/05_rings/MENU_Knowledge_05072.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: [] },
    { id: 4, name: 'Ring of Swiftness', itemType: "RING", icon: '/assets/images/icons/05_rings/MENU_Knowledge_05081.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: [] },
    { id: 5, name: 'Mind Spike Ring', itemType: "RING", icon: '/assets/images/icons/05_rings/MENU_Knowledge_05093.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: [] },
    { id: 6, name: 'Estus Ring', itemType: "RING", icon: '/assets/images/icons/05_rings/MENU_Knowledge_05103.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: [] },
    { id: 7, name: 'Ashen Estus Ring', itemType: "RING", icon: '/assets/images/icons/05_rings/MENU_Knowledge_05104.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: [] },
    { id: 8, name: 'Priests Ring', itemType: "RING", icon: '/assets/images/icons/05_rings/MENU_Knowledge_05040.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: [] },
    { id: 9, name: 'Speckled Stoneplate Ring', itemType: "RING", icon: '/assets/images/icons/05_rings/MENU_Knowledge_05035.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: [] }
  ];
  export const JUNKS: Junk[] = [
    { id: 0, name: 'Rope', itemType: "JUNK", icon: '/assets/images/icons/00_items/MENU_Knowledge_00048.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: [] },
    { id: 1, name: 'Torch', itemType: "JUNK", icon: '/assets/images/icons/00_items/MENU_Knowledge_00100.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: [] },
    { id: 2, name: 'Lockpick', itemType: "JUNK", icon: '/assets/images/icons/00_items/MENU_Knowledge_00087.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: [] },
    { id: 3, name: 'Shovel', itemType: "JUNK", icon: '/assets/images/icons/00_items/MENU_Knowledge_00153.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: [] },
    { id: 4, name: 'Parchment', itemType: "JUNK", icon: '/assets/images/icons/00_items/MENU_Knowledge_00170.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: [] },
    { id: 5, name: 'Whetstone', itemType: "JUNK", icon: '/assets/images/icons/00_items/MENU_Knowledge_00197.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: [] },
    { id: 6, name: 'Flask', itemType: "JUNK", icon: '/assets/images/icons/00_items/MENU_Knowledge_00092.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: [] },
    { id: 7, name: 'Keys', itemType: "JUNK", icon: '/assets/images/icons/00_items/MENU_Knowledge_00191.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: [] },
    { id: 8, name: 'Bones', itemType: "JUNK", icon: '/assets/images/icons/00_items/MENU_Knowledge_00041.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: [] },
    { id: 9, name: 'Portrait', itemType: "JUNK", icon: '/assets/images/icons/00_items/MENU_Knowledge_00019.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: [] }
  ];
  export const SPELLS: Spell[] = [
    { id: 0, name: 'Soul Arrow', itemType: "SPELL", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04000.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Sorcery"] },
    { id: 1, name: 'Hidden Body', itemType: "SPELL", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04014.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Sorcery"] },
    { id: 2, name: 'Cast Light', itemType: "SPELL", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04015.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Sorcery"] },
    { id: 3, name: 'Heal Aid', itemType: "SPELL", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04034.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Miracles"] },
    { id: 4, name: 'Deep Soul', itemType: "SPELL", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04099.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Hexes"] },
    { id: 5, name: 'Vow of Silence', itemType: "SPELL", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04074.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Miracles"] },
    { id: 6, name: 'Magic Barrier', itemType: "SPELL", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04011.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Sorcery"] },
    { id: 7, name: 'Combustion', itemType: "SPELL", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04028.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Pyromancy"] },
    { id: 8, name: 'Carthus Flame Arc', itemType: "SPELL", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04033.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Pyromancy"] },
    { id: 9, name: 'Bursting Fireball', itemType: "SPELL", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04021.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Pyromancy"] }
  ];
  export const ARTS: Art[] = [
    { id: 0, name: 'Charge', itemType: "ART", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04013.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: [] },
    { id: 1, name: 'Shield Splitter', itemType: "ART", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04013.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: [] },
    { id: 2, name: 'Spin Slash', itemType: "ART", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04013.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: [] },
    { id: 3, name: 'Warcry', itemType: "ART", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04013.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: [] },
    { id: 4, name: 'Perserverance', itemType: "ART", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04013.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: [] },
    { id: 5, name: 'Steady Chant', itemType: "ART", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04013.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: [] },
    { id: 6, name: 'Combustion', itemType: "ART", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04013.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: [] },
    { id: 7, name: 'Unfaltering Prayer', itemType: "ART", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04013.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: [] },
    { id: 8, name: 'Parry', itemType: "ART", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04013.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: [] },
    { id: 9, name: 'Quickstep', itemType: "ART", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04013.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: [] }
  ];
  export const FEATS: Feat[] = [
    { id: 0, name: 'Sorcerer Beginner', itemType: "FEAT", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04017.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Sorcery"] },
    { id: 1, name: 'Sorcerer Spellsword', itemType: "FEAT", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04017.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Sorcery"] },
    { id: 2, name: 'Sorcerers Knowledge', itemType: "FEAT", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04017.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Sorcery"] },
    { id: 3, name: 'Unbreakable Focus', itemType: "FEAT", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04017.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Sorcery"] },
    { id: 4, name: 'Blink', itemType: "FEAT", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04017.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Sorcery"] },
    { id: 5, name: 'Mirror Images', itemType: "FEAT", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04017.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Sorcery"] },
    { id: 6, name: 'Mind Flay', itemType: "FEAT", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04017.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Sorcery"] },
    { id: 7, name: 'Empowered Spells', itemType: "FEAT", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04017.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Sorcery"] },
    { id: 8, name: 'Moonlight Great Sword', itemType: "FEAT", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04017.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Sorcery"] },
    { id: 9, name: 'Transcend', itemType: "FEAT", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04017.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Sorcery"] },
    { id: 10, name: 'Athletic Thrusts', itemType: "FEAT", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04017.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Spear"] },
    { id: 11, name: 'Stand Back', itemType: "FEAT", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04017.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Spear"] },
    { id: 12, name: 'Improved Charge', itemType: "FEAT", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04017.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Spear"] },
    { id: 13, name: 'Acrobatics Up', itemType: "FEAT", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04017.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Dagger"] },
    { id: 14, name: 'Backstab', itemType: "FEAT", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04017.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Dagger"] },
    { id: 15, name: 'Deep Cuts', itemType: "FEAT", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04017.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Dagger"] },
    { id: 16, name: 'HP UP', itemType: "FEAT", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04017.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Hammer"] },
    { id: 17, name: 'Momentum', itemType: "FEAT", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04017.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Hammer"] },
    { id: 18, name: 'Divine Strike', itemType: "FEAT", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04017.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Hammer"] },
    { id: 19, name: 'Diplomacy', itemType: "FEAT", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04017.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Sword"] },
    { id: 20, name: 'Versatile', itemType: "FEAT", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04017.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Sword"] },
    { id: 21, name: 'Thrust', itemType: "FEAT", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04017.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Sword"] },
    { id: 22, name: 'Push', itemType: "FEAT", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04017.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Great Sword"] },
    { id: 23, name: 'Full Stomp', itemType: "FEAT", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04017.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Great Sword"] },
    { id: 24, name: 'Block', itemType: "FEAT", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04017.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Great Sword"] },
    { id: 25, name: 'Reach Behind', itemType: "FEAT", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04017.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Reaper"] },
    { id: 26, name: 'Cold Wind', itemType: "FEAT", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04017.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Reaper"] },
    { id: 27, name: 'Trip', itemType: "FEAT", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04017.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Reaper"] },
    { id: 28, name: 'Athletics Up', itemType: "FEAT", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04017.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Axe"] },
    { id: 29, name: 'Quick Kill', itemType: "FEAT", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04017.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Axe"] },
    { id: 30, name: 'Loud Cry', itemType: "FEAT", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04017.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Axe"] },
    { id: 31, name: 'Weaponless', itemType: "FEAT", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04017.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Fist"] },
    { id: 32, name: 'Thick Skin', itemType: "FEAT", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04017.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Fist"] },
    { id: 33, name: 'Knock Around', itemType: "FEAT", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04017.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Fist"] },
    { id: 34, name: 'Intercept', itemType: "FEAT", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04017.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Bow"] },
    { id: 35, name: 'Short Ranged Archery', itemType: "FEAT", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04017.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Bow"] },
    { id: 36, name: 'Roll Shot', itemType: "FEAT", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04017.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Bow"] },
    { id: 37, name: 'Stand Firm', itemType: "FEAT", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04017.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Halberd"] },
    { id: 38, name: 'Hurricane Spin', itemType: "FEAT", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04017.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Halberd"] },
    { id: 39, name: 'Two In One', itemType: "FEAT", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04017.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: ["Halberd"] }
  ];
  export const DESTINYS: Destiny[] = [
    { id: 0, name: 'Undying', itemType: "DESTINY", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04128.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: [] },
    { id: 1, name: 'Lord of Hollowing', itemType: "DESTINY", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04128.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: [] },
    { id: 2, name: 'Skilled Hollow', itemType: "DESTINY", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04128.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: [] },
    { id: 3, name: 'Caster', itemType: "DESTINY", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04128.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: [] },
    { id: 4, name: 'Worthless Husk', itemType: "DESTINY", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04128.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: [] },
    { id: 5, name: 'Free of Burden', itemType: "DESTINY", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04128.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: [] },
    { id: 6, name: 'Voice of Inspiration', itemType: "DESTINY", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04128.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: [] },
    { id: 7, name: 'Storyteller', itemType: "DESTINY", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04128.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: [] },
    { id: 8, name: 'Protege', itemType: "DESTINY", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04128.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: [] },
    { id: 9, name: 'Bloodthirsty', itemType: "DESTINY", icon: '/assets/images/icons/04_spells/MENU_Knowledge_04128.PNG', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum at leo sit amet vehicula. Nam egestas neque in ante maximus elementum. Quisque sodales pretium nisi eget lacinia. Suspendisse vulputate a neque et ullamcorper. Etiam nulla nisl, vehicula vel lorem at, maximus bibendum nibh. Integer sagittis tellus a mauris molestie elementum. Nulla facilisi. Curabitur at sollicitudin lacus, at pulvinar arcu.', tags: [] }
  ];
  export const STATS: Item[] = [
    { id: -1, name: 'Level', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -2, name: 'Souls', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -3, name: 'Fate', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -4, name: 'Hollowing', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -5, name: 'Player', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -6, name: 'Name', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -7, name: 'Gender', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -8, name: 'Starting Class', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -9, name: 'Race', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -10, name: 'Knowledge Magic', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -11, name: 'Knowledge Monsters', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -12, name: 'Knowledge World & History', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -13, name: 'Knowledge Cosmic Influence', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -14, name: 'Vitality', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -15, name: 'Endurance', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -16, name: 'Strength', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -17, name: 'Dexterity', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -18, name: 'Attunement', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -19, name: 'Intelligence', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -20, name: 'Faith', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -21, name: 'Athletics', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -22, name: 'Acrobatics', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -23, name: 'Perception', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -24, name: 'Fire Keeping', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -25, name: 'Sanity', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -26, name: 'Stealth', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -27, name: 'Precision', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -28, name: 'Diplomacy', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -29, name: 'HP', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -30, name: 'AP', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -31, name: 'FP', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -32, name: 'Flask Level', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -33, name: 'Dodge', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -34, name: 'Attunement Slots', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -35, name: 'Physical Armor', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -36, name: 'Magic Armor', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -37, name: 'Fire Armor', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -38, name: 'Lightning Armor', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -39, name: 'Dark Armor', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -40, name: 'Bleed', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -41, name: 'Poison', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -42, name: 'Toxic', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -43, name: 'Frostbite', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -44, name: 'Curse', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -45, name: 'Shield', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -46, name: 'Spear', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -47, name: 'Dagger', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -48, name: 'Hammer', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -49, name: 'Sword', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -50, name: 'Great Sword', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -51, name: 'Reaper', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -52, name: 'Axe', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -53, name: 'Fist', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -54, name: 'Bow', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -55, name: 'Halberd', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -56, name: 'Sorcery', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -57, name: 'Miracles', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -58, name: 'Pyromancy', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -59, name: 'Hexes', itemType: "STAT", icon: '', description: "", tags: [] },
    { id: -60, name: 'Dual Wielding', itemType: "STAT", icon: '', description: "", tags: [] },


  ]